spring:
  config:
    import: optional:file:.env[.properties]

  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 데이터베이스 정보 추가.
  #   - RDS 등 다른 저장소를 사용하게 되면 제거한다.
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  # H2 콘솔 활성화.
  h2:
    console:
      enabled: true

  # AI 기능을 위한 OpenAI 키 추가.
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}

  # OAuth를 위한 설정 추가.
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

# JWT를 위한 설정 추가.
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

  # 테이블 생성 후에 data.sql 실행.
  defer-datasource-initialization: true

# S3 설정.
#cloud:
#  aws:
#    region: ap-northeast-2
#    s3:
#      bucket: springboot-developer-<본인아이디>
